#!/usr/bin/env zsh
##------------------------------------------------------------------------
##
## Pinboard API CLI
##
##------------------------------------------------------------------------
##
## Installation:
##
##      $ git clone https://github.com/t1mxg0d/pinboard.zsh
##      $ chmod +x pinboard.zsh/pinboard
##      $ cp pinboard.zsh/pinboard ~/.bin/pinboard
##
#a Authentication:
##
##      Visit https://pinboard.in/settings/password and copy/paste your API Token
##      as an enviornment variable:
##
##      $ export PINBOARD_API_TOKEN="<username:apitoken>"
##
## Usage:
##
##      $ pinboard add <url>
##
##------------------------------------------------------------------------

API_HOST="https://api.pinboard.in/v1"
CURL_OPTS="--http1.1 --ipv4 --tlsv1.2 --ciphers ECDHE-ECDSA-AES256-GCM-SHA384,ECDHE-RSA-AES256-SHA384,DH-RSA-AES256-GCM-SHA384,DHE-RSA-AES256-GCM-SHA384,DHE-RSA-AES256-SHA256,ECDH-RSA-AES256-GCM-SHA384,ECDH-RSA-AES256-SHA384,AES256-GCM-SHA384"
DEBUG=false

## API -------------------------------------------------------------------

pinboard-qute-add() {
    echo "message-info \"Pinboard - Saving: $QUTE_URL[0,60]...\"" >> $QUTE_FIFO
    results="$(pinboard-add $QUTE_URL $QUTE_TITLE)"
    echo "message-info \"Pinboard - Bookmark saved $results\"" >> $QUTE_FIFO
}

pinboard-add() {
    URL="$1" && [[ -z "$URL" ]] && \
        echo "ERROR: \`api-add\` requires argument (1:URL)" && return 0
    TITLE="$2" && [[ -z "$TITLE" ]] && \
        echo "ERROR: \`api-add\` requires argument (2:TITLE)" && return 0
    # $DEBUG && echo "PINBOARD: Adding TITLE=$TITLE | URL=$URL[0,60]..."
    _api "GET" "/posts/add" "url=$URL" "description='$TITLE'"
}

## Internal functions ----------------------------------------------------

_check-deps() {
    [[ -x $(which curl) ]] || \
        echo "ERROR: Pinboard script requires curl to be installed" &&
        return 0
    return 1
}

_api() {
    _check-deps || exit

    # Arguments
    API_METHOD="$1"
    API_PATH="$API_HOST$2"
    API_PARAMS=($@[3,-1])

    # Validation
    [[ $API_METHOD =~ "(POST|PUT|GET)" ]] || \
        err="API_METHOD must be POST, GET, or PUT"
    [[ $API_PATH =~ "^$API_HOST\/\S+" ]] || \
        err="API_PATH must be an HTTP \`/path\` currently: $API_PATH"
    [[ $API_PARAMS && "$API_PARAMS" =~ "=" ]] || \
        err="API_PARAMS must be HTTP options \`key=value\` currently: $API_PARAMS"
    [[ -z "$PINBOARD_API_TOKEN" ]] &&  \
        err="Enviornment variable must be set:\r\n\r\n\texport PINBOARD_API_TOKEN\r\n\r\nYour API token is available here: https://pinboard.in/settings/password"
    [[ -n "$err" ]] && echo "ERROR: $err" && return 0

    API_DATA=(
        "--data auth_token=$PINBOARD_API_TOKEN "
        "--data format=json"
        "--data-urlencode "$^API_PARAMS[@]" "
        "-H 'Content-Type: application/json'"
        "-H 'Accept: application/json'"
    )
    eval "curl $CURL_OPTS -G $API_PATH $API_DATA"
}
    # API_PARAMS=(
    #     # "auth_token=$PINBOARD_API_TOKEN"
    #     "$API_PARAMS"
    # )
    # Debugging
    # $DEBUG && echo "PINBOARD: $API_URL"
    # Execute API call
    # curl https://api.pinboard.in/v1/posts/add\?auth_token\=dmix:9bf9ce0dc7cdecca45f8\&url\=http://conqueringthecommandline.com/book/curl\&description\="HI"
    # curl https://api.pinboard.in/v1/posts/add\?auth_token\=dmix:9bf9ce0dc7cdecca45f8\&url\="http://conqueringthecommandline.com/book/curl"\&description\="Judge sends two to prison for 7 years for H-1B fraud"
    # echo "curl -G -d  $API_PATH"
    # export CURLOPT_HTTP_VERSION="CURL_HTTP_VERSION_2TLS"
    # export CURLOPT_SSLVERSION="CURL_SSLVERSION_TLSv1_2"
    # curl --tlsv1.2 https://api.pinboard.in/v1/posts/add\?auth_token\=dmix:9bf9ce0dc7cdecca45f8
## Testing ----------------------------------------------------------------

test-add() {
    DEBUG=true
    local url="http://conqueringthecommandline.com/book/curl"
    local title="Long test tile"
    pinboard-add $url $title
}

## CLI ---------------------------------------------------------------------

[[ "$1" = ""          ]] && echo "PINBOARD: Please provide an action <test|add>"
[[ "$1" = "test"      ]] && test-add
[[ "$1" = "add"       ]] && pinboard-add $2
[[ "$1" = "qute-add"  ]] && pinboard-qute-add
